### ISSUE TITLE
how to run the project

### ISSUE THREAD

**Issue by Aaqib4021** [kunalkeshan/eVault-SIH-2023#14]
can u guide me hoe to run the project

**Comment by kunalkeshan** [comment]
Hey buddy, 

You'll be able to follow these references from previous issues to get started. 

- **General Installation and start-up**: https://github.com/kunalkeshan/eVault-SIH-2023/issues/13#issuecomment-1872565598
- **Possible backend Setup and flow**: https://github.com/kunalkeshan/eVault-SIH-2023/issues/13#issuecomment-1873173244

Do refer to the package.json file to get an idea of the scripts used to start the application (both frontend and backend).

**Comment by Aaqib4021** [comment]
bro where can use these commands npm nall?

**Comment by kunalkeshan** [comment]
In the Command Prompt / Terminal inside the project folder.

**Comment by Aaqib4021** [comment]
Thnku so mchhh bro .. i will check and update u about the same Sent from my iPhoneOn 16-Feb-2024, at 7:24 PM, Kunal Keshan ***@***.***> wrote:﻿
In the Command Prompt / Terminal inside the project folder.

**Comment by Aaqib4021** [comment]
Bro i am getting this Sent from my iPhoneOn 16-Feb-2024, at 7:53 PM, AAQIB Bashir ***@***.***> wrote:﻿Thnku so mchhh bro .. i will check and update u about the same Sent from my iPhoneOn 16-Feb-2024, at 7:24 PM, Kunal Keshan ***@***.***> wrote:﻿
In the Command Prompt / Terminal inside the project folder.

**Comment by Aaqib4021** [comment]
And getting this also bro On 16-Feb-2024, at 7:53 PM, AAQIB Bashir ***@***.***> wrote:﻿Thnku so mchhh bro .. i will check and update u about the same Sent from my iPhoneOn 16-Feb-2024, at 7:24 PM, Kunal Keshan ***@***.***> wrote:﻿
In the Command Prompt / Terminal inside the project folder.

**Comment by Aaqib4021** [comment]
i gave all the commands as u have mentioned start pnpm to npm run dev but
still getting some errors app crashed n all can u plzz check bro
or can u give me ur contact so that i can contact u on whatsapp

**Comment by kunalkeshan** [comment]
Can you send screenshots of the errors you're getting?

**Comment by Aaqib4021** [comment]
![Uploading error img.jpg…]()

**Comment by Aaqib4021** [comment]
did u got the image ?

**Comment by Aaqib4021** [comment]
u can give me ur linkdin or insta or ur whatsapp so that i can send u there

**Comment by kunalkeshan** [comment]
Thanks for attempting to share the error screenshot. It seems like the upload didn't go through properly. Could you please try uploading it again? Let's continue our conversation here in the GitHub issue. It's easier to keep track of the discussion and can also benefit others who might face similar issues. Appreciate your understanding!

**Comment by Aaqib4021** [comment]
![error img](https://github.com/kunalkeshan/eVault-SIH-2023/assets/133483248/d897610e-d53b-4faf-a322-440a1a8c9ec1)

**Comment by Aaqib4021** [comment]
this is the error

**Comment by kunalkeshan** [comment]
For now can you convert the backend typescript  code to javascript, not sure why this is happening, another person had the same issue, he's mentioned it here: https://github.com/kunalkeshan/eVault-SIH-2023/issues/13#issuecomment-1873309486
